
package VIEWS;

import javax.swing.BoxLayout;
import javax.swing.JLabel;
import CONTROLLER.RegistrarUsuarioController;
import javax.swing.BoxLayout;
import javax.swing.JLabel;


public class RegistrarUsuario extends javax.swing.JFrame {
    private RegistrarUsuarioController controller;
    

    public RegistrarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        controller = new RegistrarUsuarioController(this);
    }  
    
    // Getters para el controller
    public javax.swing.JButton getBtnRegistrar() {
        return btnRegistrar;
    }
    
    public javax.swing.JButton getBtnIniciarSesion() {
        return btnIniciarSesion;
    }
    
    public javax.swing.JTextField getNombreTxt() {
        return nombreTxt;
    }
    
    public javax.swing.JTextField getApellidoTxt() {
        return apellidoTxt;
    }
    
    public javax.swing.JTextField getCorreoTxt() {
        return correoTxt;
    }
    
    public javax.swing.JTextField getUsuarioTxt() {
        return usuarioTxt;
    }
    
    public javax.swing.JPasswordField getContrasenaTxt() {
        return contrasenaTxt;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelInterno = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        cuadroInterno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        usuario1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contrasenaTxt = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        correoTxt = new javax.swing.JTextField();
        usuario2 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        usuario3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        usuario4 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Centro de soporte del banco ");
        panelInterno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido!");
        panelInterno.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hola,");
        panelInterno.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        nombreEmpresa.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpresa.setText("BANCO");
        panelInterno.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 20));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon (1).png"))); // NOI18N
        panelInterno.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 40));

        cuadroInterno.setBackground(new java.awt.Color(0, 255, 153));
        cuadroInterno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4882066 (1).jpg"))); // NOI18N
        cuadroInterno.setText("jLabel1");
        panelInterno.add(cuadroInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 350));

        jLabel4.setText("REGISTRO DE USUARIO");
        panelInterno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        usuario.setText("CONTRASEÑA");
        usuario.setToolTipText("");
        panelInterno.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        apellidoTxt.setBorder(null);
        apellidoTxt.setName("usuarioTxt"); // NOI18N
        apellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTxtActionPerformed(evt);
            }
        });
        panelInterno.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 160, -1));

        usuario1.setText("USUARIO");
        panelInterno.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, 20));
        panelInterno.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 160, 10));

        contrasenaTxt.setBorder(null);
        contrasenaTxt.setName("contrasenaTxt"); // NOI18N
        panelInterno.add(contrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 160, -1));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setName("btnRegistrar"); // NOI18N
        panelInterno.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("¿Ya tienes cuenta?");
        panelInterno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelInterno.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        correoTxt.setBorder(null);
        correoTxt.setName("correoTxt"); // NOI18N
        correoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTxtActionPerformed(evt);
            }
        });
        panelInterno.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 160, -1));

        usuario2.setText("APELLIDO");
        usuario2.setToolTipText("");
        panelInterno.add(usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        nombreTxt.setBorder(null);
        nombreTxt.setName("usuarioTxt"); // NOI18N
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        panelInterno.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 160, -1));

        usuario3.setText("CORREO");
        usuario3.setToolTipText("");
        panelInterno.add(usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));
        panelInterno.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 160, 10));
        panelInterno.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 160, 20));
        panelInterno.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 160, 30));

        usuario4.setText("NOMBRE");
        panelInterno.add(usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 20));

        usuarioTxt.setBorder(null);
        usuarioTxt.setName("usuarioTxt"); // NOI18N
        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });
        panelInterno.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 160, -1));
        panelInterno.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, 10));

        jPanel1.add(panelInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 630, 350));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/360_F_608962534_49w9t2RcJIK45e8ETSpo0aS2rsG44SL3 (1).jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        //
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JLabel cuadroInterno;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JTextField nombreTxt;
    private java.awt.Panel panelInterno;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    private javax.swing.JLabel usuario3;
    private javax.swing.JLabel usuario4;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
