/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEWS.Admin;

import CONTROLLER.AdminReporteDesempenoController;
import java.util.List;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author CastellaSagarra
 */
public class gestEstadisticaDesempeno extends javax.swing.JPanel {

    private AdminReporteDesempenoController controller;
    
    /**
     * Creates new form gestEstadisticaDesempeno
     */
    public gestEstadisticaDesempeno() {
        initComponents();
        controller = new AdminReporteDesempenoController(this);
    }
    
    // Getters para que el controller acceda
    public javax.swing.JComboBox<String> getJComboBox1() {
        return jComboBox1;
    }
    
    public javax.swing.JButton getBtnGenerarEstadisticas() {
        return btnGenerarEstadisticas;
    }
    
    public javax.swing.JPanel getJPanelGrafico() {
        return jPanelGrafico;
    }
    
    // Método para cargar técnicos en el combo
    public void cargarTecnicosEnComboBox(List<String> tecnicos) {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    
    // Agregar placeholder
    model.addElement("-- Seleccione un técnico --");
    
    if (tecnicos != null && !tecnicos.isEmpty()) {
        for (String tecnico : tecnicos) {
            model.addElement(tecnico);
        }
    } else {
        model.addElement("No hay técnicos disponibles");
    }
    
    jComboBox1.setModel(model);
    jComboBox1.setSelectedIndex(0); // Seleccionar el placeholder
    
    jComboBox1.revalidate();
    jComboBox1.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarEstadisticas = new javax.swing.JButton();
        jPanelGrafico = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Estadistica de Desempeño");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione un Empleado:");

        btnGenerarEstadisticas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGenerarEstadisticas.setText("Generar Estadisticas");
        btnGenerarEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarEstadisticasActionPerformed(evt);
            }
        });

        jPanelGrafico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(525, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnGenerarEstadisticas)))
                        .addGap(86, 434, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarEstadisticas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarEstadisticasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarEstadisticas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelGrafico;
    // End of variables declaration//GEN-END:variables

}


