package VIEWS.Admin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import MODELS.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author GerardRG
 */
public class gestVerSolicitud extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    private javax.swing.JTextArea txtDescripcion;

    /**
     * Creates new form verSolicitud
     */
    public gestVerSolicitud() {
        initComponents();
        inicializarTabla();
        cargarDatos();
        
        txtDescripcion = new javax.swing.JTextArea();
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setEditable(false);
        SCPInformacion.setViewportView(txtDescripcion);
    }
    
    private void inicializarTabla() {
        modelo = new DefaultTableModel();
        String[] columnas = {
            "ID", "Fecha Registro", "Descripción", "Cliente",
            "Categoría", "Prioridad", "Estado", "Asignado A"
        };
        modelo.setColumnIdentifiers(columnas);
        jTable1.setModel(modelo);

        // Inicializar el combo correctamente
        CMBcategorias.setModel(new javax.swing.DefaultComboBoxModel<>( 
            new String[] { "Todos", "Acceso", "Rendimiento", "Errores", "Consultas" }
        ));
    }

    private void cargarDatos() {
        cargarDatos(0); // 0 = todos
    }

    private void cargarDatos(int filtroCategoria) {
        Connection con = DatabaseConnection.getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la BD");
            return;
        }

        String sql = "SELECT id, fecha_registro, descripcion, creada_por, "
                   + "categoria_id, prioridad_id, estado_id, asignado_a_id "
                   + "FROM public.solicitudes";

        // Si se selecciona una categoría específica, agregar filtro
        if (filtroCategoria > 0) {
            sql += " WHERE categoria_id = '" + filtroCategoria + "'";
        }

        try (PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            modelo.setRowCount(0);

            while (rs.next()) {
                // Asignación directa de las columnas como String
                String categoria = rs.getString("categoria_id");
                String prioridad = rs.getString("prioridad_id");
                String estado = rs.getString("estado_id");
                String asignado = rs.getString("asignado_a_id");

                // Mostrar los datos en la tabla
                Object[] fila = {
                    rs.getString("id"),
                    rs.getTimestamp("fecha_registro"),
                    rs.getString("descripcion"),
                    rs.getString("creada_por"),
                    categoria,
                    prioridad,
                    estado,
                    asignado
                };
                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        } finally {
            DatabaseConnection.closeConnection(con);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnVerSolicitud = new javax.swing.JButton();
        CMBcategorias = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        SCPInformacion = new javax.swing.JScrollPane();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Información de solicitudes");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("Descripcion");

        btnCerrar.setText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha Registro", "Descripción", "Nombre", "Categoria ", "Prioridad", "Estado", "Asignado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Bucar ID");

        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVerSolicitud.setText("Ver");
        btnVerSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSolicitudActionPerformed(evt);
            }
        });

        CMBcategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CMBcategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CMBcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBcategoriasActionPerformed(evt);
            }
        });

        jLabel2.setText("Ordenar por categorias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CMBcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SCPInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(btnVerSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(CMBcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SCPInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnVerSolicitud))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idBuscar = txtBuscar.getText().trim();

        if (idBuscar.isEmpty()) {
            cargarDatos();
            txtDescripcion.setText("");
            return;
        }

        Connection con = DatabaseConnection.getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la BD");
            return;
        }

        String sql = "SELECT id, fecha_registro, descripcion, creada_por, " +
                     "categoria_id, prioridad_id, estado_id, asignado_a_id " +
                     "FROM public.solicitudes WHERE id = ?";

        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, idBuscar);
            try (ResultSet rs = ps.executeQuery()) {
                modelo.setRowCount(0); 

                if (rs.next()) {
                    String categoria = rs.getString("categoria_id");
                    String prioridad = rs.getString("prioridad_id");
                    String estado = rs.getString("estado_id");

                    // Mostrar los datos en la tabla
                    Object[] fila = {
                        rs.getString("id"),
                        rs.getTimestamp("fecha_registro"),
                        rs.getString("descripcion"),
                        rs.getString("creada_por"),
                        categoria,
                        prioridad,
                        estado,
                        rs.getString("asignado_a_id")
                    };
                    modelo.addRow(fila);

                    // Mostrar los detalles en el JTextArea
                    txtDescripcion.setText(
                        "ID: " + rs.getString("id") + "\n" +
                        "Fecha: " + rs.getTimestamp("fecha_registro") + "\n" +
                        "Cliente: " + rs.getString("creada_por") + "\n" +
                        "Categoría: " + categoria + "\n" +
                        "Prioridad: " + prioridad + "\n" +
                        "Estado: " + estado + "\n" +
                        "Asignado a: " + rs.getString("asignado_a_id") + "\n\n" +
                        "Descripción:\n" + rs.getString("descripcion")
                    );
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el ID ingresado");
                    txtDescripcion.setText("");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en búsqueda: " + e.getMessage());
        } finally {
            DatabaseConnection.closeConnection(con);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVerSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSolicitudActionPerformed
      int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una solicitud");
            return;
        }

        // Obtener el ID de la solicitud seleccionada
        String idSolicitud = (String) modelo.getValueAt(fila, 0);

        Connection con = DatabaseConnection.getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la BD");
            return;
        }

        String sql = "SELECT id, fecha_registro, descripcion, creada_por, "
                   + "categoria_id, prioridad_id, estado_id, asignado_a_id "
                   + "FROM public.solicitudes WHERE id = ?";

        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, idSolicitud);  // Aseguramos que el ID sea tratado como String
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String categoria = rs.getString("categoria_id");
                String prioridad = rs.getString("prioridad_id");
                String estado = rs.getString("estado_id");
                String asignado = rs.getString("asignado_a_id");

                // Mostrar en cascada dentro del JTextArea
                txtDescripcion.setText(
                    "ID: " + rs.getString("id") + "\n" +
                    "Fecha de registro: " + rs.getTimestamp("fecha_registro") + "\n" +
                    "Cliente: " + rs.getString("creada_por") + "\n" +
                    "Categoría: " + categoria + "\n" +
                    "Prioridad: " + prioridad + "\n" +
                    "Estado: " + estado + "\n" +
                    "Asignado a: " + asignado + "\n\n" +
                    "Descripción:\n" + rs.getString("descripcion")
                );
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar solicitud: " + e.getMessage());
        } finally {
            DatabaseConnection.closeConnection(con);
        }   
    }//GEN-LAST:event_btnVerSolicitudActionPerformed

    private void CMBcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBcategoriasActionPerformed
      int index = CMBcategorias.getSelectedIndex();
        cargarDatos(index);
        
    }//GEN-LAST:event_CMBcategoriasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CMBcategorias;
    private javax.swing.JScrollPane SCPInformacion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVerSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
