
package VIEWS.Admin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import CONTROLLER.AdminUsuarioListaController;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.Timer;



public class gestUsuarioLista extends javax.swing.JPanel {

    private DefaultTableModel modeloTabla;    
    private AdminUsuarioListaController controller;
    private Timer autoRefreshTimer;
    
    public gestUsuarioLista() {
        initComponents();
        configurarTabla();
        controller = new AdminUsuarioListaController(this);
        controller.setModeloTabla(modeloTabla);
        controller.cargarUsuarios();
        configurarAncestorListener();
        iniciarActualizacionAutomatica();
    }
    private void iniciarActualizacionAutomatica() {
        autoRefreshTimer = new Timer(25000, e -> { // 25000 ms = 25 segundos
            System.out.println("🔄 Actualización automática de lista de usuarios...");
            controller.cargarUsuarios();
        });
        autoRefreshTimer.start();
        System.out.println("✅ Actualización automática iniciada (cada 25 segundos - lista usuarios)");
    }
    
    private void configurarAncestorListener() {
        this.addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                System.out.println("🔍 Panel agregado a la jerarquía - Actualizando tabla lista usuarios...");
                controller.cargarUsuarios();
            }
            
            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }
            
            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
    }
    
    private void configurarTabla() {
    modeloTabla = new DefaultTableModel(
    new Object[][]{},
    new String[]{"ID", "Nombre", "Usuario", "Rol"}
    ) {
    @Override public boolean isCellEditable(int row, int column) { return false; }
    };
    tblListaUsuarios.setModel(modeloTabla);

    }
    
    public javax.swing.JButton getBtnEditarUsuario() {
        return btnEditarUsuario;
    }
    
    public javax.swing.JButton getBtnEliminarUsuario() {
        return btnEliminarUsuario;
    }
    
    public javax.swing.JTable getTblListaUsuarios() {
        return tblListaUsuarios;
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaUsuarios = new javax.swing.JTable();
        btnEliminarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Lista de Usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        tblListaUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Usuario", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tblListaUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 530, 370));

        btnEliminarUsuario.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash_120980.png")));
        btnEliminarUsuario.setText("");
        btnEliminarUsuario.setToolTipText("Eliminar usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        btnEliminarUsuario.setText("");
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 100, 40));

        btnEditarUsuario.setBackground(new java.awt.Color(0, 153, 0));
        btnEditarUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditarUsuario.setText("");
        btnEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarUsuario.setMaximumSize(new java.awt.Dimension(94, 29));
        btnEditarUsuario.setMinimumSize(new java.awt.Dimension(94, 29));
        btnEditarUsuario.setPreferredSize(new java.awt.Dimension(94, 29));
        btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/writing.png")));
        btnEditarUsuario.setText("");
        btnEditarUsuario.setToolTipText("Editar usuario");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaUsuarios;
    // End of variables declaration//GEN-END:variables
}
