/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEWS.Admin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import MODELS.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Camara
 */
public class gestUsuarioLista extends javax.swing.JPanel {

    /**
     * Creates new form gestUsuarioListas
     */
    
    private DefaultTableModel modeloTabla;
    
    public gestUsuarioLista() {
        initComponents();
        configurarTabla();
        cargarUsuarios();
    }
    
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Nombre", "Usuario", "Rol"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
        tblListaUsuarios.setModel(modeloTabla);
    }
    
    public void cargarUsuarios() {
        // Limpiar tabla antes de cargar nuevos datos
        modeloTabla.setRowCount(0);

        String sql = "SELECT id_usuario, nombre, apellido, username, rol_id FROM public.usuarios WHERE activo = true ORDER BY id_usuario";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id_usuario");
                String nombre = rs.getString("nombre");
                //String apellido = rs.getString("apellido");
                String usuario = rs.getString("username");
                int rolId = rs.getInt("rol_id");

                // Convertir rol_id a nombre de rol
                String nombreRol = convertirRol(rolId);

                // Combinar nombre y apellido
                String nombreCompleto = nombre + " " ;

                // Agregar fila a la tabla
                modeloTabla.addRow(new Object[]{id, nombreCompleto, usuario, nombreRol});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar usuarios: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Para debugging
        }
    }
    
    private String convertirRol(int rolId) {
        switch (rolId) {
            case 1: return "Administrador";
            case 2: return "Técnico";
            case 3: return "Usuario";
            default: return "Desconocido";
        }
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaUsuarios = new javax.swing.JTable();
        btnEliminarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Lista de Usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        tblListaUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Usuario", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 410, 270));

        btnEliminarUsuario.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash_120980.png")));
        btnEliminarUsuario.setText("");
        btnEliminarUsuario.setToolTipText("Eliminar usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        btnEliminarUsuario.setText("");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, 40));

        btnEditarUsuario.setBackground(new java.awt.Color(0, 153, 0));
        btnEditarUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditarUsuario.setText("");
        btnEditarUsuario.setMaximumSize(new java.awt.Dimension(94, 29));
        btnEditarUsuario.setMinimumSize(new java.awt.Dimension(94, 29));
        btnEditarUsuario.setPreferredSize(new java.awt.Dimension(94, 29));
        btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/writing.png")));
        btnEditarUsuario.setText("");
        btnEditarUsuario.setToolTipText("Editar usuario");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, 40));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reload_refresh_update_icon_134497.png")));
        btnActualizar.setText("");
        btnActualizar.setToolTipText("Actualizar datos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        btnActualizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 70, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaUsuarios;
    // End of variables declaration//GEN-END:variables
}
