/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Designs.Admin;

import org.jdesktop.swingx.JXDatePicker;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Date;

/**
 *
 * @author CastellaSagarra
 */
public class gestReporteSolicitud extends javax.swing.JPanel {

    
    /**
     * Creates new form gestReporteSolicitud
     */
    public gestReporteSolicitud() {
        initComponents();
        configurarDatePickers();
    }
    
    //Validacion seleccion fecha maximo fecha actual
    private void configurarDatePickers() {
    dateFin.getMonthView().setUpperBound(new Date());
    dateInicio.getMonthView().setUpperBound(new Date());
    
    dateInicio.setFormats("dd/MM/yyyy");
    dateFin.setFormats("dd/MM/yyyy");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReporteSolicitud = new javax.swing.JLabel();
        txtaFechaInicio = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JLabel();
        txtTipoSolicitud = new javax.swing.JLabel();
        cmbTipoSolicitud = new javax.swing.JComboBox<>();
        btnGenerarReporte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dateInicio = new org.jdesktop.swingx.JXDatePicker();
        dateFin = new org.jdesktop.swingx.JXDatePicker();

        txtReporteSolicitud.setBackground(new java.awt.Color(0, 0, 0));
        txtReporteSolicitud.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        txtReporteSolicitud.setText("Reporte de Solicitud");

        txtaFechaInicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtaFechaInicio.setText("Fecha de Inicio:");

        txtFechaFin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFechaFin.setText("Fecha de Fin:");

        txtTipoSolicitud.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTipoSolicitud.setText("Tipo de Solicitud:");

        cmbTipoSolicitud.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Solicitud de Informacion", "Solicitud de Soporte", "Solicitud de Permisos" }));

        btnGenerarReporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGenerarReporte.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        dateFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarReporte)
                    .addComponent(cmbTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoSolicitud)
                    .addComponent(txtFechaFin)
                    .addComponent(txtaFechaInicio)
                    .addComponent(txtReporteSolicitud)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtReporteSolicitud)
                .addGap(18, 18, 18)
                .addComponent(txtaFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtTipoSolicitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarReporte)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<String> cmbTipoSolicitud;
    private org.jdesktop.swingx.JXDatePicker dateFin;
    private org.jdesktop.swingx.JXDatePicker dateInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtFechaFin;
    private javax.swing.JLabel txtReporteSolicitud;
    private javax.swing.JLabel txtTipoSolicitud;
    private javax.swing.JLabel txtaFechaInicio;
    // End of variables declaration//GEN-END:variables
}
