/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Designs.Admin;


import Designs.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Camara
 */
public class gestUsuarioEditar extends javax.swing.JPanel {

    /**
     * Creates new form gestUsuarioEditar
     */
    public gestUsuarioEditar() {
        initComponents();
        limpiarCampos();
    }
    
    private void limpiarCampos() {
    // Array de componentes para limpiar
    javax.swing.JComponent[] componentes = {
        jtfNombre, jtfApellido, jtfUsuario, jtfCorreo, jpfContrasena
    };    
    // Limpiar campos de texto
    for (javax.swing.JComponent componente : componentes) {
        if (componente instanceof javax.swing.JTextField) {
            ((javax.swing.JTextField) componente).setText("");
        } else if (componente instanceof javax.swing.JPasswordField) {
            ((javax.swing.JPasswordField) componente).setText("");
        }
    }    
    // Restablecer combo box
    cmbRol.setSelectedIndex(0);
    }
    
    private boolean validarCampos() {
    // Array de campos a validar con sus mensajes
    javax.swing.JTextField[] campos = {
        jtfNombre, jtfApellido, jtfUsuario, jtfCorreo
    };    
    String[] mensajes = {
        "Nombre", "Apellido", "Usuario", "Correo"
    };    
    // Validar campos obligatorios
    for (int i = 0; i < campos.length; i++) {
        if (campos[i].getText().trim().isEmpty()) {
            mostrarError("El campo " + mensajes[i] + " es obligatorio", campos[i]);
            return false;
        }
    }    
    // Validar contraseña
    if (String.valueOf(jpfContrasena.getPassword()).isEmpty()) {
        mostrarError("El campo Contraseña es obligatorio", jpfContrasena);
        return false;
    }    
    // Validar formato de email
    String correo = jtfCorreo.getText().trim();
    if (!correo.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
        mostrarError("Por favor ingrese un correo electrónico válido", jtfCorreo);
        return false;
    }    
        return true;
    }
    
    private void mostrarError(String mensaje, java.awt.Component componente) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        componente.requestFocus();
    }
    
    private void agregarUsuario() {
        if (!validarCampos()) {
            return;
        }
    
    // Usar try-with-resources para manejo automático de recursos
        String sql = "INSERT INTO usuarios (nombre, apellido, username, correo, contrasena, rol_id) VALUES (?, ?, ?, ?, ?, ?)";
    
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        // Establecer parámetros
            pstmt.setString(1, jtfNombre.getText().trim());
            pstmt.setString(2, jtfApellido.getText().trim());
            pstmt.setString(3, jtfUsuario.getText().trim());
            pstmt.setString(4, jtfCorreo.getText().trim());
            pstmt.setString(5, new String(jpfContrasena.getPassword()));
            pstmt.setInt(6, obtenerRolId());
        
        // Ejecutar inserción
        int filasAfectadas = pstmt.executeUpdate();
        
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "Usuario agregado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al agregar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    private int obtenerRolId() {
        String rolSeleccionado = (String) cmbRol.getSelectedItem();
    
        // Usar Map para mapeo más eficiente
        java.util.Map<String, Integer> roles = new java.util.HashMap<>();
        roles.put("Tecnico", 2);
        roles.put("Programador", 2);
        roles.put("Empleado", 3);
    
        return roles.getOrDefault(rolSeleccionado, 3); // Valor por defecto: Empleado
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jpfContrasena = new javax.swing.JPasswordField();
        cmbRol = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnAgregarUsuario = new javax.swing.JButton();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfCorreo = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTitulo.setText("Agregar Usuario");

        jpfContrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Tecnico", "Programador" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblApellido.setText("Apellido:");

        lblContrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblContrasena.setText("Contraseña:");

        lblRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRol.setText("Rol:");

        lblCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCorreo.setText("Correo:");

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        btnAgregarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        jtfNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfNombre.setText("jTextField1");
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfApellido.setText("jTextField2");

        jtfCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfCorreo.setText("jTextField3");

        jtfUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfUsuario.setText("jTextField4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(lblContrasena)
                    .addComponent(lblUsuario)
                    .addComponent(jtfUsuario)
                    .addComponent(jpfContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRol)
                    .addComponent(lblApellido)
                    .addComponent(jtfApellido)
                    .addComponent(lblCorreo)
                    .addComponent(jtfCorreo)
                    .addComponent(cmbRol, 0, 261, Short.MAX_VALUE))
                .addGap(236, 236, 236))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnAgregarUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(49, 49, 49)
                        .addComponent(lblNombre)
                        .addGap(12, 12, 12)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellido)
                        .addGap(18, 18, 18)
                        .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addGap(17, 17, 17)
                        .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRol)
                        .addGap(13, 13, 13)
                        .addComponent(cmbRol))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblContrasena)
                        .addGap(17, 17, 17)
                        .addComponent(jpfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88)
                .addComponent(btnAgregarUsuario)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
       agregarUsuario();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JPasswordField jpfContrasena;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
